[package]
name = "local-sketch-deck"
version = "0.1.0"
description = "A local visual workshop for tiny interactive cards"
authors = ["Param Factory"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
