const slug = 'local-sketch-deck';
const api = `https://api.sociobot.in/api/v1/products/${slug}`;
const button = document.querySelector<HTMLAnchorElement>('#downloadButton')!;
const note = document.querySelector<HTMLElement>('#releaseNote')!;
const detected = () => /Windows/i.test(navigator.userAgent) ? 'Windows' : /Mac/i.test(navigator.userAgent) ? 'macOS' : 'Linux';
async function latest() { try { const r = await fetch('https://github.com/B-Divyesh/sf-local-sketch-deck/releases/latest/download/latest.json'); if (!r.ok) throw Error(); const manifest: { version?: string; platforms?: Record<string, { url?: string }> } = await r.json(); const os = detected(); const url = manifest.platforms?.[os]?.url; if (!url) throw Error(); button.href = url; button.textContent = `Download for ${os}`; note.textContent = `${manifest.version || 'Latest release'} · unsigned installer · checksums included`; } catch { note.textContent = `Choose a release for ${detected()} on GitHub. Installers are unsigned.`; } }
function save(token: string) { localStorage.setItem(`sb_license:${slug}`, token); localStorage.setItem(`sb_license_checked:${slug}`, '0'); }
async function verify(token: string, status: HTMLElement) { const checked = Number(localStorage.getItem(`sb_license_checked:${slug}`) || 0); const cached = localStorage.getItem(`sb_license_valid:${slug}`); if (cached === 'true') status.textContent = 'Supporter license restored. Checking quietly in the background…'; if (Date.now() - checked < 86400000) return; try { const r = await fetch(`${api}/verify?license=${encodeURIComponent(token)}`); const v = await r.json(); localStorage.setItem(`sb_license_checked:${slug}`, String(Date.now())); localStorage.setItem(`sb_license_valid:${slug}`, String(v.valid)); status.textContent = v.valid ? 'Supporter license active.' : 'This license is no longer active. You can purchase a new one above.'; } catch { status.textContent = cached === 'true' ? 'Supporter license restored offline; we’ll check later.' : 'Could not verify while offline. Your free editor remains available.'; } }
const params = new URLSearchParams(location.search), returned = params.get('license'); if (returned) { save(returned); history.replaceState({}, '', location.pathname + location.hash); }
const status = document.querySelector<HTMLElement>('#licenseStatus')!; const token = returned || localStorage.getItem(`sb_license:${slug}`); if (token) verify(token, status);
document.querySelector<HTMLFormElement>('#restore')!.onsubmit = e => { e.preventDefault(); const value = document.querySelector<HTMLInputElement>('#license')!.value.trim(); if (!value) { status.textContent = 'Paste your license token first.'; return; } save(value); verify(value, status); };
latest();
