const slug = 'local-sketch-deck';
const api = `https://api.sociobot.in/api/v1/products/${slug}`;
const button = document.querySelector<HTMLAnchorElement>('#downloadButton')!;
const note = document.querySelector<HTMLElement>('#releaseNote')!;
const detected = () => /Windows/i.test(navigator.userAgent) ? 'Windows' : /Mac/i.test(navigator.userAgent) ? 'macOS' : 'Linux';
async function latest() { try { const r = await fetch('https://api.github.com/repos/B-Divyesh/sf-local-sketch-deck/releases/latest'); if (!r.ok) throw Error(); const release = await r.json(); const manifestAsset = release.assets?.find((a: { name: string }) => a.name === 'latest.json'); let manifest: { version?: string; platforms?: Record<string, { url?: string }> } | undefined; if (manifestAsset?.url) { try { const m = await fetch(manifestAsset.url, { headers: { Accept: 'application/octet-stream' } }); if (m.ok) manifest = await m.json(); } catch { /* release asset listing remains a safe fallback */ } } const os = detected(); const match = os === 'macOS' ? /\.dmg$/ : os === 'Windows' ? /\.(msi|exe)$/ : /\.(AppImage|deb)$/; const asset = manifest?.platforms?.[os]?.url ? { browser_download_url: manifest.platforms[os].url } : release.assets?.find((a: { name: string }) => match.test(a.name)); if (!asset?.browser_download_url) throw Error(); button.href = asset.browser_download_url; button.textContent = `Download for ${os}`; note.textContent = `${manifest?.version || release.tag_name} · unsigned installer · checksums included`; } catch { note.textContent = `Choose a release for ${detected()} on GitHub. Installers are unsigned.`; } }
function save(token: string) { localStorage.setItem(`sb_license:${slug}`, token); localStorage.setItem(`sb_license_checked:${slug}`, '0'); }
async function verify(token: string, status: HTMLElement) { const checked = Number(localStorage.getItem(`sb_license_checked:${slug}`) || 0); const cached = localStorage.getItem(`sb_license_valid:${slug}`); if (cached === 'true') status.textContent = 'Supporter license restored. Checking quietly in the background…'; if (Date.now() - checked < 86400000) return; try { const r = await fetch(`${api}/verify?license=${encodeURIComponent(token)}`); const v = await r.json(); localStorage.setItem(`sb_license_checked:${slug}`, String(Date.now())); localStorage.setItem(`sb_license_valid:${slug}`, String(v.valid)); status.textContent = v.valid ? 'Supporter license active.' : 'This license is no longer active. You can purchase a new one above.'; } catch { status.textContent = cached === 'true' ? 'Supporter license restored offline; we’ll check later.' : 'Could not verify while offline. Your free editor remains available.'; } }
const params = new URLSearchParams(location.search), returned = params.get('license'); if (returned) { save(returned); history.replaceState({}, '', location.pathname + location.hash); }
const status = document.querySelector<HTMLElement>('#licenseStatus')!; const token = returned || localStorage.getItem(`sb_license:${slug}`); if (token) verify(token, status);
document.querySelector<HTMLFormElement>('#restore')!.onsubmit = e => { e.preventDefault(); const value = document.querySelector<HTMLInputElement>('#license')!.value.trim(); if (!value) { status.textContent = 'Paste your license token first.'; return; } save(value); verify(value, status); };
latest();
