import './style.css';
import { blankProject, exportHtml, projectJson, sampleProject, uid, validateProject, type ActionKind, type DeckElement, type Project } from './project';

const q = <T extends Element = HTMLElement>(s: string) => document.querySelector(s) as T;
const studio = q<HTMLElement>('#studio'), start = q<HTMLElement>('#startScreen'), stage = q<HTMLElement>('#stage'), cards = q<HTMLElement>('#cardList'), inspect = q<HTMLElement>('#inspectorContent'), toast = q<HTMLElement>('#toast');
let project: Project | null = null, selectedCard = 0, selectedElement: string | null = null;
let dirty = false;
const currentCard = () => project!.cards[selectedCard];
const flash = (message: string) => { toast.textContent = message; toast.classList.add('show'); window.setTimeout(() => toast.classList.remove('show'), 2600); };
const clean = (s: string) => s.replace(/[<>&]/g, c => ({ '<':'&lt;', '>':'&gt;', '&':'&amp;' }[c]!));

function openDeck(p: Project) { project = p; selectedCard = 0; selectedElement = null; dirty = false; start.hidden = true; studio.hidden = false; render(); }
function markDirty() { dirty = true; render(); }
function render() { if (!project) return; q('#projectName').textContent = project.name + (dirty ? ' • unsaved' : ''); renderCards(); renderStage(); renderInspector(); }
function renderCards() { cards.innerHTML = project!.cards.map((card, i) => `<button class="card-tab ${i === selectedCard ? 'active' : ''}" data-card="${i}" role="listitem"><span class="swatch" style="background:${card.color}"></span><span>${clean(card.title)}</span><small>${card.elements.length}</small></button>`).join(''); cards.querySelectorAll<HTMLButtonElement>('[data-card]').forEach(b => b.onclick = () => { selectedCard = Number(b.dataset.card); selectedElement = null; render(); }); }
function renderStage() { const card = currentCard(); stage.style.background = card.color; stage.innerHTML = card.elements.map(e => `<div class="canvas-el ${e.kind} ${e.hidden ? 'is-hidden':''} ${selectedElement === e.id ? 'selected':''}" data-el="${e.id}" style="left:${e.x}%;top:${e.y}%;width:${e.w}%;height:${e.h}%" tabindex="0" role="${e.kind === 'button' ? 'button' : 'group'}" aria-label="${clean(e.text) || e.kind}">${e.kind === 'image' && e.src ? `<img src="${e.src}" alt="${clean(e.text) || 'Project image'}">` : clean(e.text)}</div>`).join(''); stage.querySelectorAll<HTMLElement>('[data-el]').forEach(el => { el.onclick = () => { selectedElement = el.dataset.el!; render(); }; el.onkeydown = ev => { if (ev.key === 'Enter' || ev.key === ' ') { ev.preventDefault(); selectedElement = el.dataset.el!; render(); } }; }); }
function targets() { return currentCard().elements.map(e => `<option value="${e.id}">${clean(e.text || e.kind)} (${e.id.slice(-4)})</option>`).join(''); }
function renderInspector() { const card = currentCard(), e = card.elements.find(x => x.id === selectedElement); if (!e) { inspect.innerHTML = `<p class="eyebrow">INSPECTOR</p><h2>${clean(card.title)}</h2><label>Card title<input id="cardTitle" value="${clean(card.title)}"></label><label>Card colour<input id="cardColor" type="color" value="${card.color}"></label><p class="muted">Select an item on the card to edit its words, place, and one action.</p>`; q<HTMLInputElement>('#cardTitle').oninput = ev => { card.title = (ev.target as HTMLInputElement).value; markDirty(); }; q<HTMLInputElement>('#cardColor').oninput = ev => { card.color = (ev.target as HTMLInputElement).value; markDirty(); }; return; }
  const a = e.action || { type: 'goToCard' as ActionKind }; const actionOptions = [['show','Show an item'],['hide','Hide an item'],['changeText','Change text'],['playSound','Play a sound'],['goToCard','Go to a card']].map(([v,l]) => `<option value="${v}" ${a.type === v ? 'selected':''}>${l}</option>`).join('');
  inspect.innerHTML = `<p class="eyebrow">${e.kind.toUpperCase()} • INSPECTOR</p><h2>Make it clear</h2><label>Accessible text${e.kind === 'text' ? '<textarea id="elText">'+clean(e.text)+'</textarea>' : '<input id="elText" value="'+clean(e.text)+'">'}</label><div class="coords"><label>X<input id="elX" type="number" min="0" max="95" value="${e.x}"></label><label>Y<input id="elY" type="number" min="0" max="95" value="${e.y}"></label><label>Width<input id="elW" type="number" min="5" max="100" value="${e.w}"></label><label>Height<input id="elH" type="number" min="5" max="100" value="${e.h}"></label></div><hr><h3>When clicked or focused</h3><label>Action<select id="actionType">${actionOptions}</select></label><div id="actionDetails"></div><button id="deleteEl" class="danger">Delete this item</button>`;
  const update = () => { e.text = q<HTMLInputElement>('#elText').value; e.x = Number(q<HTMLInputElement>('#elX').value); e.y = Number(q<HTMLInputElement>('#elY').value); e.w = Number(q<HTMLInputElement>('#elW').value); e.h = Number(q<HTMLInputElement>('#elH').value); markDirty(); }; ['#elText','#elX','#elY','#elW','#elH'].forEach(s => q<HTMLInputElement>(s).oninput = update);
  const actionType = q<HTMLSelectElement>('#actionType'); const details = q<HTMLElement>('#actionDetails'); const actionFields = () => { const type = actionType.value as ActionKind; e.action = { type, target: e.action?.target, value: e.action?.value }; if (type === 'playSound') { details.innerHTML = '<p class="muted">A short, local synth tone plays. No audio is uploaded.</p>'; } else if (type === 'changeText') { details.innerHTML = `<label>New text<input id="actionValue" value="${clean(e.action.value || '')}"></label><label>Text item<select id="actionTarget">${targets()}</select></label>`; } else if (type === 'goToCard') { details.innerHTML = `<label>Destination card<select id="actionTarget">${project!.cards.map(c => `<option value="${c.id}" ${e.action?.target === c.id ? 'selected':''}>${clean(c.title)}</option>`).join('')}</select></label>`; } else { details.innerHTML = `<label>Item<select id="actionTarget">${targets()}</select></label>`; } const target = details.querySelector<HTMLSelectElement>('#actionTarget'); if (target) target.value = e.action?.target || target.value, target.oninput = () => { e.action!.target = target.value; markDirty(); }; const value = details.querySelector<HTMLInputElement>('#actionValue'); if (value) value.oninput = () => { e.action!.value = value.value; markDirty(); }; }; actionType.oninput = () => { actionFields(); markDirty(); }; actionFields(); q<HTMLButtonElement>('#deleteEl').onclick = () => { if (confirm(`Delete “${e.text || e.kind}”?`)) { card.elements = card.elements.filter(x => x.id !== e.id); selectedElement = null; markDirty(); } }; }
function addElement(kind: DeckElement['kind'], extra: Partial<DeckElement> = {}) { const e: DeckElement = { id: uid(kind), kind, x: 12, y: 18 + currentCard().elements.length * 10, w: kind === 'button' ? 32 : 70, h: kind === 'button' ? 12 : 14, text: kind === 'button' ? 'A new button' : kind === 'text' ? 'Write something here.' : 'Project image', ...extra }; currentCard().elements.push(e); selectedElement = e.id; markDirty(); }
function download(name: string, content: string, type: string) { const blob = new Blob([content], { type }); const a = document.createElement('a'); a.href = URL.createObjectURL(blob); a.download = name; a.click(); URL.revokeObjectURL(a.href); }
async function imageFile(file: File) { if (file.size > 2_000_000) { flash('Choose an image under 2 MB for a portable project.'); return; } const reader = new FileReader(); reader.onload = () => addElement('image', { src: String(reader.result), w: 42, h: 34 }); reader.readAsDataURL(file); }
function tone() { try { const ac = new AudioContext(), o = ac.createOscillator(), g = ac.createGain(); o.frequency.value = 660; g.gain.setValueAtTime(.06, ac.currentTime); g.gain.exponentialRampToValueAtTime(.001, ac.currentTime + .15); o.connect(g).connect(ac.destination); o.start(); o.stop(ac.currentTime + .15); } catch { flash('Your browser prevented sound; interact with the page first.'); } }
function preview() { let cardIndex = selectedCard; let state: Record<string, Partial<DeckElement>> = {}; const dialog = q<HTMLDialogElement>('#previewDialog'), root = q<HTMLElement>('#previewStage'); const draw = () => { const card = project!.cards[cardIndex]; root.style.background = card.color; root.innerHTML = card.elements.filter(e => !state[e.id]?.hidden).map(e => `<${e.kind === 'button' ? 'button' : 'div'} data-play="${e.id}" class="play-el ${e.kind}" style="left:${e.x}%;top:${e.y}%;width:${e.w}%;height:${e.h}%">${e.kind === 'image' && e.src ? `<img src="${e.src}" alt="${clean(e.text)}">` : clean((state[e.id]?.text as string) || e.text)}</${e.kind === 'button' ? 'button' : 'div'}>`).join(''); root.querySelectorAll<HTMLElement>('[data-play]').forEach(n => n.onclick = () => { const e = card.elements.find(x => x.id === n.dataset.play)!; const a = e.action; if (!a) return; if (a.type === 'goToCard') { const next = project!.cards.findIndex(c => c.id === a.target); if (next >= 0) { cardIndex = next; state = {}; } } else if (a.type === 'playSound') tone(); else if (a.target) state[a.target] = { ...state[a.target], ...(a.type === 'show' ? {hidden:false} : a.type === 'hide' ? {hidden:true} : a.type === 'changeText' ? {text:a.value || ''} : {}) }; draw(); }); }; draw(); dialog.showModal(); }
q('#createSample').onclick = () => openDeck(sampleProject()); q('#createBlank').onclick = () => openDeck(blankProject()); q('#newProject').onclick = () => { if (!project || !dirty || confirm('Start a new deck? Unsaved work will remain unsaved.')) openDeck(blankProject()); }; q('#addCard').onclick = () => { project!.cards.push({ id: uid('card'), title: `Card ${project!.cards.length + 1}`, color: '#fff6df', elements: [] }); selectedCard = project!.cards.length - 1; selectedElement = null; markDirty(); }; q('#addText').onclick = () => addElement('text'); q('#addButton').onclick = () => addElement('button'); q<HTMLInputElement>('#addImage').onchange = ev => { const f = (ev.target as HTMLInputElement).files?.[0]; if (f) imageFile(f); }; q('#saveProject').onclick = () => { if (project) { download(`${project.name.toLowerCase().replace(/[^a-z0-9]+/g, '-') || 'deck'}.sketchdeck`, projectJson(project), 'application/json'); dirty = false; render(); flash('Project downloaded. Choose its location; existing files are never overwritten.'); } }; q('#exportProject').onclick = () => { if (project) { download(`${project.name.toLowerCase().replace(/[^a-z0-9]+/g, '-') || 'deck'}.html`, exportHtml(project), 'text/html'); flash('Standalone HTML exported.'); } }; q('#openProject').onclick = () => q<HTMLInputElement>('#openFile').click(); q<HTMLInputElement>('#openFile').onchange = ev => { const f = (ev.target as HTMLInputElement).files?.[0]; if (!f) return; const r = new FileReader(); r.onload = () => { try { const data = JSON.parse(String(r.result)); if (!validateProject(data)) throw new Error(); openDeck(data); flash(`Opened ${f.name}.`); } catch { flash('That file is not a Local Sketch Deck project.'); } }; r.readAsText(f); }; q('#previewProject').onclick = preview; q('#closePreview').onclick = () => q<HTMLDialogElement>('#previewDialog').close(); document.addEventListener('keydown', ev => { if ((ev.ctrlKey || ev.metaKey) && ev.key.toLowerCase() === 's' && project) { ev.preventDefault(); q<HTMLButtonElement>('#saveProject').click(); } if (ev.key === 'Delete' && selectedElement && project && !['INPUT','TEXTAREA','SELECT'].includes((document.activeElement?.tagName || ''))) { const c = currentCard(); c.elements = c.elements.filter(e => e.id !== selectedElement); selectedElement = null; markDirty(); } });
